# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python
python:
  - "3.5"
  - "3.6"

# https://docs.travis-ci.com/user/languages/python/#Testing-Against-Multiple-Versions-of-Dependencies-(e.g.-Django-or-Flask)
# env:
#   - TOXENV=py35
#   - TOXENV=py36

install: pip install tox

script: tox

notifications:
  email: false
